//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Nome { get; set; }
        public string Matricula { get; set; }
        public string NomeSupervisor { get; set; }
        public string MatriculaSupervisor { get; set; }
        public string Equipe { get; set; }
        public int PerfilId { get; set; }
        public string NomeUsuario { get; set; }
        public int UsuarioId { get; set; }
        public bool NotificacaoEvento { get; set; }
        public bool NotificacaoPipeline { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
